/* ---------------------------------------------------------
SECTION 1: GEOGRAPHICAL MARKET ANALYSIS AND GLOBAL SALES 
PERFORMANCE EVALUATION

Objective: To obtain data-driven insights by comprehensively analyzing 
country-based order volumes and revenue distribution in order to 
prioritize logistics operations, identify regional performance 
differences, and develop sustainable market growth strategies.
   --------------------------------------------------------- */

EVALUATE
SUMMARIZECOLUMNS(
    Sales[Country],
    "Total Orders", DISTINCTCOUNT(Sales[InvoiceNo]),
    "Total Revenue", [Total Revenue]
)


/* ---------------------------------------------------------
SECTION 2: SALES TIMING AND ADVERTISING STRATEGY 
PERFORMANCE ANALYSIS

Objective: To obtain data-driven insights by analyzing 
order intensity based on time patterns, identifying the time 
periods with the highest sales performance, optimizing advertising 
budgets effectively, and directing marketing resources in line 
with data-driven strategies.
   --------------------------------------------------------- */

EVALUATE
VAR FilteredTable = FILTER('Sales', 'Sales'[Quantity] > 0)
VAR HourlyTable = SELECTCOLUMNS(FilteredTable
, "SalesHour", HOUR('Sales'[InvoiceDate])
, "InvoiceNo", 'Sales'[InvoiceNo]
, "Revenue", 'Sales'[Quantity] * 'Sales'[UnitPrice])
RETURN
GROUPBY(
    HourlyTable,
    [SalesHour],
    "Total Sales", COUNTX(CURRENTGROUP(), [InvoiceNo]),
    "Total Revenue", SUMX(CURRENTGROUP(), [Revenue])
)
ORDER BY [Total Revenue] DESC  


/* ---------------------------------------------------------
SECTION 3: PRODUCT PERFORMANCE AND INVENTORY STRATEGY 
ANALYSIS

Objective: To obtain data-driven insights by identifying 
the Top 10 highest-performing products based on sales volume and 
revenue performance, analyzing popular products, optimizing 
inventory management processes, and uncovering cross-selling 
opportunities through data-driven approaches.
   --------------------------------------------------------- */

EVALUATE
VAR FilteredTable = FILTER('Sales', 'Sales'[Quantity] > 0)
VAR SummaryTable = 
    SUMMARIZE(
        FilteredTable,
        'Sales'[Description],
        "Total Units Sold", SUM('Sales'[Quantity]),
        "Toplam Ciro", ROUND(SUMX('Sales', 'Sales'[Quantity] * 'Sales'[UnitPrice]), 2),
        "Sipariş Sayısı", DISTINCTCOUNT('Sales'[InvoiceNo])
    )
RETURN
    SummaryTable
ORDER BY [TotalUnitsSold] DESC 


/* ---------------------------------------------------------
SECTION 4: CUSTOMER LOYALTY AND VIP SEGMENTATION 
ANALYSIS

Objective: To identify the Top 10 highest-performing 
customers based on spending amount and purchase frequency, 
analyze customer behaviors, and develop loyalty programs and 
customer retention strategies based on the obtained data-driven 
insights.
   --------------------------------------------------------- */

EVALUATE
VAR CustomerSummary = 
    SUMMARIZE(
        FILTER('Sales', NOT(ISBLANK('Sales'[Number of Customers])) && 'Sales'[Quantity] > 0),
        'Sales'[Number of Customers],
        "Total Visits", DISTINCTCOUNT('Sales'[InvoiceNo]),
        "Total Quantity Purchased", SUM('Sales'[Quantity]),
        "Total Revenue Generated", ROUND(SUMX('Sales', 'Sales'[Quantity] * 'Sales'[UnitPrice]), 2)
    )
RETURN
    TOPN(10, CustomerSummary, [Total Revenue Generated])
ORDER BY [Total Revenue Generated] DESC
















